import { Query, type Connection, type Pool, type PoolClient, type QueryConfig } from "pg";

// Only names generated by lib/prisma.ts belong to this one-shot lifecycle.
// Keep their uniqueness: the local bridge has shared statements across TCP
// clients. Give each query an equally unique portal, close its own statement
// after Execute and BEFORE Sync in the same batch, then clear pg's local cache.
// This compatibility hook is tested against installed pg 8.22; revalidate on upgrades.
const OWN_STATEMENT = /^bttb_[a-z0-9]+_[a-z0-9]+_[a-f0-9]{16}$/;
const POOL_MARK = Symbol.for("bttb.local-statement-cleanup.pool.v1");
const CLIENT_MARK = Symbol.for("bttb.local-statement-cleanup.client.v1");
export const STATEMENT_CLOSE_TIMEOUT_MS = 5_000;

type Callback = (error: Error | null, result?: unknown) => void;
type DriverQuery = (config: unknown, values?: unknown, callback?: Callback) => unknown;
type WireConnection = Connection & { parsedStatements: Record<string, string> };
type ManagedClient = PoolClient & {
  [CLIENT_MARK]?: boolean;
  end(): Promise<void>;
};

/** Retry resource closure after an extended-protocol error skipped the initial
 * Close. This queued Close/Sync cycle is not SQL. It cannot
 * clear another query's plan, commit/rollback a transaction, or edit game data.
 * Use pg's public Submittable Query extension; do not patch pg's prototypes.
 */
function closeStatement(client: ManagedClient, original: DriverQuery, name: string): Promise<void> {
  return new Promise((resolve, reject) => {
    let connection: WireConnection | undefined;
    let settled = false;
    const close = new Query("", (error) => {
      if (settled) return;
      settled = true;
      if (error) { reject(error); return; }
      // pg keeps this JS cache separately from the backend's prepared plans.
      if (connection) delete connection.parsedStatements[name];
      resolve();
    });
    Object.assign(close, { query_timeout: STATEMENT_CLOSE_TIMEOUT_MS });
    close.submit = (wire: Connection) => {
      connection = wire as WireConnection;
      wire.close({ type: "S", name }, false);
      wire.sync();
    };
    try { original.call(client, close); } catch (error) { reject(error); }
  });
}

function instrumentClient(client: PoolClient) {
  const managed = client as ManagedClient;
  if (managed[CLIENT_MARK]) return;
  const original = client.query as DriverQuery;
  const wrapped: DriverQuery = (config, values, callback) => {
    if (!config || typeof config !== "object" || "submit" in config ||
        !("name" in config) || typeof config.name !== "string" ||
        !OWN_STATEMENT.test(config.name) || !("text" in config) ||
        typeof config.text !== "string" || !config.text.trim()) {
      return original.call(client, config, values, callback);
    }
    const name = config.name;
    const text = config.text;
    const configuredCallback = "callback" in config ? config.callback : undefined;
    const selected = typeof values === "function" ? values : callback ?? configuredCallback;
    if (selected !== undefined && typeof selected !== "function") {
      return original.call(client, config, values, callback);
    }
    const done = selected as Callback | undefined;
    const promise = new Promise<unknown>((resolve, reject) => {
      let received = false;
      const completed: Callback = (queryError, result) => {
        // Some transports can notify an error and subsequently finish reading.
        if (received) return;
        received = true;
        const clearCache = () => {
          delete (managed as unknown as { connection: WireConnection }).connection.parsedStatements[name];
        };
        // Success already closed the statement before the original Sync.
        if (!queryError) { clearCache(); resolve(result); return; }
        // Extended-protocol errors skip commands until Sync, so retry only
        // the Close after that boundary without changing transaction status.
        void closeStatement(managed, original, name).then(() => {
          clearCache(); reject(queryError);
        }, (cleanupError: unknown) => {
          // Never return a connection with an unconfirmed cleanup to the pool.
          // This ends only this driver's physical connection, not the DB service.
          void managed.end().catch(() => {});
          reject(queryError ?? new Error("Local prepared statement cleanup failed.", { cause: cleanupError }));
        });
      };
      try {
        if ("rows" in config && config.rows) {
          throw new Error("Paged queries are not supported by the local one-shot adapter.");
        }
        const queryConfig: QueryConfig & { portal: string; callback?: undefined } = {
          ...config, name, text, portal: name, callback: undefined,
        };
        const request = new Query(queryConfig,
          (typeof values === "function" ? undefined : values) as unknown[] | undefined,
          (error, result) => completed(error ?? null, result));
        if ("query_timeout" in config) Object.assign(request, { query_timeout: config.query_timeout });
        // Prisma does not use pg's streaming/paginated query mode here. Keep
        // Execute, Close and Sync in the same corked protocol batch.
        const native = request as Query & { _getRows: (wire: Connection, rows?: number) => void };
        if (typeof native._getRows !== "function") throw new Error("Unsupported pg query protocol implementation.");
        native._getRows = (wire, rows) => {
          if (rows) throw new Error("Paged queries are not supported by the local one-shot adapter.");
          wire.execute({ portal: name }, false);
          wire.close({ type: "S", name }, false);
          wire.sync();
        };
        original.call(client, request);
      } catch (error) { completed(error instanceof Error ? error : new Error(String(error))); }
    });
    if (!done) return promise;
    void promise.then(result => done(null, result), (error: Error) => done(error));
    return undefined;
  };
  client.query = wrapped as typeof client.query;
  managed[CLIENT_MARK] = true;
}

/** Enable only for the known local Prisma bridge, never for hosted PostgreSQL.
 * acquire covers a reused hot-reload pool as well as newly connected clients.
 * Re-importing this module cannot wrap a client or register hooks twice.
 */
export function installLocalStatementCleanup(pool: Pool): void {
  const managed = pool as Pool & { [POOL_MARK]?: boolean };
  if (managed[POOL_MARK]) return;
  pool.on("connect", instrumentClient);
  pool.on("acquire", instrumentClient);
  managed[POOL_MARK] = true;
}
